name: collab-vm-server CI 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
      # recursively checkout, we need to do this in order to properly compile
          submodules: 'recursive'
    - name: Cache vcpkg tree
      uses: actions/cache@v1.0.3
      id: cache-vcpkg
      with:
        path: "~/vcpkg"
        key: vcpkg
    - name: Install vcpkg and boost if needed
      env:
        CACHE_HIT: ${{steps.cache-vcpkg.outputs.cache-hit}}
      run: |
        if [[ "$CACHE_HIT" == '' ]]; then
            git clone https://github.com/Microsoft/vcpkg
            cd vcpkg
            ./bootstrap-vcpkg.sh -disableMetrics
            ./vcpkg install boost:x64-linux
            cd ..
        fi
    - name: Install vcpkg and boost if needed
      run: sudo apt install make -y
    - name: Generate CMake build files
      run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$HOME/vcpkg/scripts/buildsystems/vcpkg.cmake
    - name: Build collab-vm-server
      run: cd build && make -j3
    - name: Upload collab-vm-server
      uses: actions/upload-artifact@v1
      with:
        path: build/collab-vm-server